import { NgZone } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
export declare class NgxForce {
    private http;
    private zone;
    private loginURL;
    private scopeParameters;
    private appId;
    private apiVersion;
    private oauth;
    private tokenStore;
    private context;
    private serverURL;
    private baseURL;
    private proxyURL;
    private oauthCallbackURL;
    private useProxy;
    private deferredLogin;
    private onlyOne;
    init(params: any): void;
    login(): Promise<{}>;
    private loginWithBrowser();
    private loginWithDevice();
    private parseQueryString(queryString);
    private oauthCallback(url);
    getUserId(): any;
    isAuthenticated(): boolean;
    private getRequestBaseURL();
    private toQueryString(obj);
    private refreshToken();
    request(obj: any): Promise<{}>;
    query(soql: any): Promise<{}>;
    retrieve(objectName: any, id: any, fields: any): Promise<{}>;
    create(objectName: any, data: any): Promise<{}>;
    update(objectName: any, data: any): Promise<{}>;
    del(objectName: any, id: any): Promise<{}>;
    upsert(objectName: any, externalIdField: any, externalId: any, data: any): Promise<{}>;
    constructor(http: Http, zone: NgZone);
    ngOnDestroy(): void;
}
